Improve isolation between Zope and ZServer layers.
Without these changes the ZServer layer implicitly uses the Zope app in some
places. This breaks tests later on which run on the Zope layer with the
following traceback:

    Traceback (most recent call last):
      ...
      File ".../plone/testing/zope.py", line 244, in zopeApp
        app = addRequestContainer(Zope2.app(connection), environ=environ)
      File ".../Zope2/__init__.py", line 55, in app
        return bobo_application(*args, **kw)
    TypeError: 'NoneType' object is not callable